In [1]:
import pandas as pd

In [2]:
data_areas =pd.read_csv("Bhopal_area.csv")

In [3]:
data_areas

           area_name emoji        lat        lng
0    Gulmohar Colony     🌳  23.193673  77.435483
1          Indrapuri     🏡  23.250214  77.465986
2       Arera Colony    🏙️  23.213054  77.437476
3       Arera Colony    🏙️  23.217541  77.438384
4          Bairagarh     🕌  23.286640  77.353973
5    Gulmohar Colony     🌳  23.184832  77.434612
6           MP Nagar     🏢  23.229000  77.436000
7           MP Nagar     🏢  23.217207  77.427456
8           VIP Road     🌅  23.242292  77.381774
9           MP Nagar     🏢  23.230698  77.431837
10      Arera Colony    🏙️  23.215500  77.406500
11        New Market    🛍️  23.220500  77.430500
12   Gulmohar Colony     🌳  23.190500  77.435500
13          Old City    🏛️  23.248000  77.397000
14          TT Nagar     🏬  23.240000  77.410000
15     10 No. Market     🛒  23.213500  77.437000
16      Arera Colony    🏙️  23.215000  77.435000
17     10 No. Market     🛒  23.213800  77.436500
18      Arera Colony    🏙️  23.218000  77.439000
19          Kohefiza    🏞️  23.260000  77.380000
20          VIP Road     🌅  23.257200  77.367800
21     10 No. Market     🛒  23.207000  77.436500
22        Kolar Road    🛣️  23.173100  77.432600
23          MP Nagar     🏢  23.216600  77.426900
24     Ayodhya Nagar     🏡  23.250600  77.526500
25      Arera Colony    🏙️  23.220000  77.440000
26      Arera Colony    🏙️  23.212000  77.438000
27      Arera Colony    🏙️  23.210000  77.435000
28  Hoshangabad Road    🛣️  23.230000  77.445000
29  Hoshangabad Road    🛣️  23.240000  77.450000
30          VIP Road     🌅  23.260000  77.370000
31          VIP Road     🌅  23.258000  77.368000
32          MP Nagar     🏢  23.235000  77.430000
33          TT Nagar     🏬  23.245000  77.400000
34     Shivaji Nagar    🏘️  23.230500  77.420500
35          Old City    🏛️  23.255000  77.395000
36          MP Nagar     🏢  23.229500  77.436500
37        Govindpura     🏭  23.260500  77.410500
38          Kohefiza    🏞️  23.260000  77.380500
39      Arera Colony    🏙️  23.215500  77.432100
40     10 No. Market     🛒  23.213000  77.436000
41          TT Nagar     🏬  23.240500  77.410500
42          VIP Road     🌅  23.257100  77.367900
43     Ashoka Garden     🌳  23.250000  77.420000
44      Arera Colony    🏙️  23.220500  77.435500
45          MP Nagar     🏢  23.225500  77.438500
46          MP Nagar     🏢  23.230500  77.440500
47  Hoshangabad Road    🛣️  23.235500  77.445500
48      Arera Colony    🏙️  23.215500  77.438500
49  Hoshangabad Road    🛣️  23.240500  77.450500
50          MP Nagar     🏢  23.229500  77.436500
51      Arera Colony    🏙️  23.215500  77.438000
52        Kolar Road    🛣️  23.240500  77.390000
53          MP Nagar     🏢  23.225000  77.430000
54  Hoshangabad Road    🛣️  23.240500  77.450500
55         Indrapuri     🏡  23.250500  77.460500
56     Ayodhya Nagar     🏡  23.260500  77.470500
57         BHEL Area     🏭  23.270500  77.480500
58           Piplani     🏭  23.280500  77.490500
59       Anand Nagar     🏠  23.290500  77.500500

In [4]:
data = pd.read_csv("bhopal_cold_cafe_spot_name.csv")

In [5]:
data_areas["label"] = data_areas["emoji"] + " " + data_areas["area_name"]

In [6]:
data_areas

           area_name emoji        lat        lng                label
0    Gulmohar Colony     🌳  23.193673  77.435483    🌳 Gulmohar Colony
1          Indrapuri     🏡  23.250214  77.465986          🏡 Indrapuri
2       Arera Colony    🏙️  23.213054  77.437476      🏙️ Arera Colony
3       Arera Colony    🏙️  23.217541  77.438384      🏙️ Arera Colony
4          Bairagarh     🕌  23.286640  77.353973          🕌 Bairagarh
5    Gulmohar Colony     🌳  23.184832  77.434612    🌳 Gulmohar Colony
6           MP Nagar     🏢  23.229000  77.436000           🏢 MP Nagar
7           MP Nagar     🏢  23.217207  77.427456           🏢 MP Nagar
8           VIP Road     🌅  23.242292  77.381774           🌅 VIP Road
9           MP Nagar     🏢  23.230698  77.431837           🏢 MP Nagar
10      Arera Colony    🏙️  23.215500  77.406500      🏙️ Arera Colony
11        New Market    🛍️  23.220500  77.430500        🛍️ New Market
12   Gulmohar Colony     🌳  23.190500  77.435500    🌳 Gulmohar Colony
13          Old City    🏛️  23.248000  77.397000          🏛️ Old City
14          TT Nagar     🏬  23.240000  77.410000           🏬 TT Nagar
15     10 No. Market     🛒  23.213500  77.437000      🛒 10 No. Market
16      Arera Colony    🏙️  23.215000  77.435000      🏙️ Arera Colony
17     10 No. Market     🛒  23.213800  77.436500      🛒 10 No. Market
18      Arera Colony    🏙️  23.218000  77.439000      🏙️ Arera Colony
19          Kohefiza    🏞️  23.260000  77.380000          🏞️ Kohefiza
20          VIP Road     🌅  23.257200  77.367800           🌅 VIP Road
21     10 No. Market     🛒  23.207000  77.436500      🛒 10 No. Market
22        Kolar Road    🛣️  23.173100  77.432600        🛣️ Kolar Road
23          MP Nagar     🏢  23.216600  77.426900           🏢 MP Nagar
24     Ayodhya Nagar     🏡  23.250600  77.526500      🏡 Ayodhya Nagar
25      Arera Colony    🏙️  23.220000  77.440000      🏙️ Arera Colony
26      Arera Colony    🏙️  23.212000  77.438000      🏙️ Arera Colony
27      Arera Colony    🏙️  23.210000  77.435000      🏙️ Arera Colony
28  Hoshangabad Road    🛣️  23.230000  77.445000  🛣️ Hoshangabad Road
29  Hoshangabad Road    🛣️  23.240000  77.450000  🛣️ Hoshangabad Road
30          VIP Road     🌅  23.260000  77.370000           🌅 VIP Road
31          VIP Road     🌅  23.258000  77.368000           🌅 VIP Road
32          MP Nagar     🏢  23.235000  77.430000           🏢 MP Nagar
33          TT Nagar     🏬  23.245000  77.400000           🏬 TT Nagar
34     Shivaji Nagar    🏘️  23.230500  77.420500     🏘️ Shivaji Nagar
35          Old City    🏛️  23.255000  77.395000          🏛️ Old City
36          MP Nagar     🏢  23.229500  77.436500           🏢 MP Nagar
37        Govindpura     🏭  23.260500  77.410500         🏭 Govindpura
38          Kohefiza    🏞️  23.260000  77.380500          🏞️ Kohefiza
39      Arera Colony    🏙️  23.215500  77.432100      🏙️ Arera Colony
40     10 No. Market     🛒  23.213000  77.436000      🛒 10 No. Market
41          TT Nagar     🏬  23.240500  77.410500           🏬 TT Nagar
42          VIP Road     🌅  23.257100  77.367900           🌅 VIP Road
43     Ashoka Garden     🌳  23.250000  77.420000      🌳 Ashoka Garden
44      Arera Colony    🏙️  23.220500  77.435500      🏙️ Arera Colony
45          MP Nagar     🏢  23.225500  77.438500           🏢 MP Nagar
46          MP Nagar     🏢  23.230500  77.440500           🏢 MP Nagar
47  Hoshangabad Road    🛣️  23.235500  77.445500  🛣️ Hoshangabad Road
48      Arera Colony    🏙️  23.215500  77.438500      🏙️ Arera Colony
49  Hoshangabad Road    🛣️  23.240500  77.450500  🛣️ Hoshangabad Road
50          MP Nagar     🏢  23.229500  77.436500           🏢 MP Nagar
51      Arera Colony    🏙️  23.215500  77.438000      🏙️ Arera Colony
52        Kolar Road    🛣️  23.240500  77.390000        🛣️ Kolar Road
53          MP Nagar     🏢  23.225000  77.430000           🏢 MP Nagar
54  Hoshangabad Road    🛣️  23.240500  77.450500  🛣️ Hoshangabad Road
55         Indrapuri     🏡  23.250500  77.460500          🏡 Indrapuri
56     Ayodhya Nagar     🏡  23.260500  77.470500      🏡 Ayodhya Nagar
57         BHEL Area     🏭  23.270500  77.480500          🏭 BHEL Area
58           Piplani     🏭  23.280500  77.490500            🏭 Piplani
59       Anand Nagar     🏠  23.290500  77.500500        🏠 Anand Nagar

In [7]:
data_areas.to_csv("bhopal_areas_label.csv")

In [8]:
def rating_star(rating):
     return "⭐" * int(rating)
rating_star(2)

'⭐⭐'

In [9]:
icons = ["🏠","🛒","🚚","☕"]
def get_spot_type_icon(spot_type):
      if spot_type == "cafe":
          return "🏠"
      elif spot_type == "cart":
          return "🛒"
      elif spot_type == "truck":
          return "🚚"
      else:
          return "☕"
get_spot_type_icon("home")

'☕'

In [10]:
from geopy.distance import geodesic

In [11]:
user_location = (25.180392, 55.254501)
spot_location = (25.1850, 55.2600)
distance = geodesic(user_location, spot_location).km
distance

0.753533519070546

In [12]:
def calculate_distance(row):
    lat = row["lat"]
    lng = row["lng"]
    spot_location = (lat,lng)
    dis = geodesic(user_location, spot_location).km
    return round(dis, 2)
data["distance_km"] = data.apply(calculate_distance, axis=1)

In [13]:
from datetime import datetime

In [14]:
def is_open_spot(row):
    current_time = datetime.now().strftime("%H:%M")
    opening_time = row["opening_time"]
    closing_time = row["closing_time"]
    if opening_time <= current_time <= closing_time:
        return "open"
    else:
        return "closed"
data["is_open"] = data.apply(is_open_spot, axis=1)

In [15]:
rows = data.iloc[0:2]
for ind,row in rows.iterrows():
    print(row["name"],row["distance_km"],row["type"])

Nothing Before Coffee Gulmohar 2261.84 cafe
Nothing Before Coffee Indrapuri 2263.82 cafe